# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI Practice

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: ["dev"]

permissions:
  contents: read


jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    ## JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
        
    # secret 파일 로딩
    - uses: actions/checkout@v3
    - run: touch ./src/main/resources/application-dev.properties
    - run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application-dev.properties
    - run: cat ./src/main/resources/application-dev.properties
      
    # Gradle 캐싱
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |  
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
      
    # Gradle 권한 설정
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
      
    # Gradle Build
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
